# minikube ssh
#                          _             _            
#             _         _ ( )           ( )           
#   ___ ___  (_)  ___  (_)| |/')  _   _ | |_      __  
# /' _ ` _ `\| |/' _ `\| || , <  ( ) ( )| '_`\  /'__`\
# | ( ) ( ) || || ( ) || || |\`\ | (_) || |_) )(  ___/
# (_) (_) (_)(_)(_) (_)(_)(_) (_)`\___/'(_,__/'`\____)

# $ mkdir pod-volume
# $ cd pod-volume/
# $ pwd
# /home/docker/pod-volume
# exit

apiVersion: v1
kind: Pod
metadata:
  name: share-pod
  labels:
    app: share-pod
spec:
  volumes:
  - name: host-volume
    hostPath:
      path:  /home/docker/pod-volume
  containers:
  - image: nginx
    name: nginx
    ports:
      - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: host-volume
  - image: debian
    name: debian
    volumeMounts:
    - mountPath: /host-vol
      name: host-volume
    command: ["/bin/sh", "-c", "echo Intro to K8S > /host-vol/index.html; sleep 3600"]