apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
  labels:
    app: nginx
    type: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        type: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80